// <auto-generated />
using System;
using Convocatorias.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Convocatorias.Infraestructure.Migrations
{
    [DbContext(typeof(ConvocatoriasDbContext))]
    partial class ConvocatoriasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Convocatorias.Domain.Entities.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Candidatos", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Convocatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer");

                    b.Property<int>("FacultadId")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Convocatorias", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ConvocatoriaPeriodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AsignadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConvocatoriaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsActual")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConvocatoriaId");

                    b.ToTable("ConvocatoriaPeriodo");
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EducacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExperienciaDocenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExperienciaInvExtId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EducacionId");

                    b.HasIndex("ExperienciaDocenteId");

                    b.HasIndex("ExperienciaInvExtId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Educacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioGraduacion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CandidatoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PosgradoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PosgradoStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TipoFormacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TituloGrado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Educaciones", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ExperienciaDocente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AniosExperiencia")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CandidatoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DesdePeriodo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HastaPeriodo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("ExperienciasDocentes", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ExperienciaInvExt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CandidatoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ParticipoComo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TieneExperiencia")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("ExperienciasInvExt", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Periodos", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Postulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConvocatoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ConvocatoriaId", "CandidatoId")
                        .IsUnique();

                    b.ToTable("Postulaciones", (string)null);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ConvocatoriaPeriodo", b =>
                {
                    b.HasOne("Convocatorias.Domain.Entities.Convocatoria", null)
                        .WithMany("Periodos")
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Convocatorias.Domain.Entities.Educacion", null)
                        .WithMany("Documentos")
                        .HasForeignKey("EducacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Convocatorias.Domain.Entities.ExperienciaDocente", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ExperienciaDocenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Convocatorias.Domain.Entities.ExperienciaInvExt", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ExperienciaInvExtId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Educacion", b =>
                {
                    b.HasOne("Convocatorias.Domain.Entities.Candidato", null)
                        .WithMany("Educaciones")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ExperienciaDocente", b =>
                {
                    b.HasOne("Convocatorias.Domain.Entities.Candidato", null)
                        .WithMany("ExperienciasDocente")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ExperienciaInvExt", b =>
                {
                    b.HasOne("Convocatorias.Domain.Entities.Candidato", null)
                        .WithMany("ExperienciasInvExt")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Postulacion", b =>
                {
                    b.HasOne("Convocatorias.Domain.Entities.Candidato", null)
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Convocatorias.Domain.Entities.Convocatoria", null)
                        .WithMany()
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Educaciones");

                    b.Navigation("ExperienciasDocente");

                    b.Navigation("ExperienciasInvExt");
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Convocatoria", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.Educacion", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ExperienciaDocente", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Convocatorias.Domain.Entities.ExperienciaInvExt", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
